channels:
  - gimli
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_llvm
  - appdirs=1.4.3=py_1
  - attrs=19.3.0=py_0
  - binutils_impl_linux-64=2.33.1=h53a641e_8
  - binutils_linux-64=2.33.1=h9595d00_16
  - bzip2=1.0.8=h516909a_2
  - ca-certificates=2019.11.28=hecc5488_0
  - certifi=2019.11.28=py36_0
  - curl=7.68.0=hf8cf82a_0
  - cycler=0.10.0=py_2
  - dbus=1.13.6=he372182_0
  - expat=2.2.9=he1b5a44_2
  - fontconfig=2.13.1=he4413a7_1000
  - freetype=2.10.0=he983fc9_1
  - future=0.18.2=py36_0
  - gcc_impl_linux-64=7.3.0=hd420e75_5
  - gcc_linux-64=7.3.0=h553295d_16
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=py36h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_2
  - gstreamer=1.14.5=h36ae1b5_2
  - gxx_impl_linux-64=7.3.0=hdf63c60_5
  - gxx_linux-64=7.3.0=h553295d_16
  - hdf4=4.2.13=hf30be14_1003
  - hdf5=1.10.5=nompi_h3c11f04_1104
  - icu=58.2=hf484d3e_1000
  - imageio=2.8.0=py_0
  - importlib_metadata=1.5.0=py36_0
  - jpeg=9c=h14c3975_1001
  - jsoncpp=1.8.4=hc9558a2_1002
  - kiwisolver=1.1.0=py36hc9558a2_0
  - krb5=1.16.4=h2fd8d38_0
  - ld_impl_linux-64=2.33.1=h53a641e_8
  - libblas=3.8.0=15_openblas
  - libboost=1.67.0=h46d08c1_4
  - libcblas=3.8.0=15_openblas
  - libcurl=7.68.0=hda55be3_0
  - libedit=3.1.20170329=hf8c457e_1001
  - libffi=3.2.1=he1b5a44_1006
  - libgcc-ng=9.2.0=h24d8f2e_2
  - libgfortran-ng=7.3.0=hdf63c60_5
  - libgomp=9.2.0=h24d8f2e_2
  - libiconv=1.15=h516909a_1005
  - liblapack=3.8.0=15_openblas
  - libnetcdf=4.6.2=h303dfb8_1003
  - libopenblas=0.3.8=h5ec1e0e_0
  - libpng=1.6.37=hed695b0_0
  - libssh2=1.8.2=h22169c7_2
  - libstdcxx-ng=9.2.0=hdf63c60_2
  - libtiff=4.1.0=hc3755c2_3
  - libuuid=2.32.1=h14c3975_1000
  - libxcb=1.13=h14c3975_1002
  - libxml2=2.9.9=h13577e0_2
  - llvm-openmp=9.0.1=hc9558a2_2
  - lz4-c=1.8.3=he1b5a44_1001
  - matplotlib=3.1.1=py36_0
  - matplotlib-base=3.1.1=py36hfd891ef_0
  - metis=5.1.0=he1b5a44_1005
  - more-itertools=8.2.0=py_0
  - ncurses=6.1=hf484d3e_1002
  - numpy=1.16.5=py36h95a1406_0
  - olefile=0.46=py_0
  - openblas=0.3.8=he1df0ab_0
  - openssl=1.1.1d=h516909a_0
  - packaging=20.1=py_0
  - pcre=8.44=he1b5a44_0
  - pillow=7.0.0=py36hefe7db6_0
  - pip=20.0.2=py_2
  - pluggy=0.12.0=py_0
  - pthread-stubs=0.4=h14c3975_1001
  - py=1.8.1=py_0
  - py-boost=1.67.0=py36h04863e7_4
  - pygimli=1.0.12=np116py36hf484d3e_1
  - pyparsing=2.4.6=py_0
  - pyqt=5.9.2=py36hcca6a23_4
  - pytest=5.3.5=py36_1
  - python=3.6.7=h357f687_1006
  - python-dateutil=2.8.1=py_0
  - pyvista=0.22.4=py_0
  - qt=5.9.7=h52cfd70_2
  - readline=8.0=hf8c457e_0
  - scipy=1.4.1=py36h921218d_0
  - scooby=0.5.2=py_0
  - setuptools=45.2.0=py36_0
  - sip=4.19.8=py36hf484d3e_1000
  - six=1.14.0=py36_0
  - sqlite=3.30.1=hcee41ef_0
  - suitesparse=5.6.0=h717dc36_0
  - tbb=2019.9=hc9558a2_1
  - tk=8.6.10=hed695b0_0
  - tornado=6.0.3=py36h516909a_4
  - vtk=8.2.0=py36hfdee58b_203
  - wcwidth=0.1.8=py_0
  - wheel=0.34.2=py_1
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.9=h516909a_0
  - xorg-libxau=1.0.9=h14c3975_0
  - xorg-libxdmcp=1.1.3=h516909a_0
  - xorg-libxt=1.2.0=h516909a_0
  - xorg-xproto=7.0.31=h14c3975_1007
  - xz=5.2.4=h14c3975_1001
  - zipp=3.0.0=py_0
  - zlib=1.2.11=h516909a_1006
  - zstd=1.4.4=h3b9ef0a_1
